vimc/orderly-web

src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/Helpers.kt, src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/controllers/api/ArtefactController.kt, src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/controllers/api/ResourceController.kt, src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/integration_tests/tests/ArtefactTests.kt, src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/integration_tests/tests/OnetimeTokenTests.kt, src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/integration_tests/tests/ResourceTests.kt, src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/unit_tests/controllers/ArtefactControllerTests.kt, src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/unit_tests/controllers/ResourceControllerTests.kt
This is already in Reporting API:
https://github.com/vimc/montagu-reporting-api/pull/67/files
=> i2728 Adding change to allowing download of files with spaces in names

src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/security/authentication/GithubAuthenticator.kt, src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/security/GithubAuthenticatorTests.kt
Changes to authenticator. This will break the tests, and will also be a pain to merge with mrc-210
=> Mrc-203 Authentication error with github org and team set 

.gitignore, src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/app_start/APIErrorHandler.kt, src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/app_start/ErrorHandler.kt, src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/app_start/Router.kt, src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/app_start/SparkApp.kt, src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/app_start/WebErrorHandler.kt, src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/errors/UnexpectedError.kt, src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/integration_tests/helpers/RequestHelper.kt, src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/integration_tests/tests/RoutingTests.kt, src/app/src/test/resources/config.properties, src/app/templates/error.ftl, src/config/default.properties, src/customConfigTests/build.gradle, src/customConfigTests/src/test/kotlin/org/vaccineimpact/orderlyweb/customConfigTests/CustomConfigTests.kt, src/customConfigTests/src/test/kotlin/org/vaccineimpact/orderlyweb/customConfigTests/GithubWebTests.kt, src/customConfigTests/src/test/kotlin/org/vaccineimpact/orderlyweb/customConfigTests/MontaguAuthenticationTests.kt, src/customConfigTests/src/test/kotlin/org/vaccineimpact/orderlyweb/customConfigTests/RequestHelper.kt, src/customConfigTests/src/test/resources/config.properties
Adds generic error page for web errors. Also I moved the Montagu auth tests to the custom config tests so  package so that they don't depend on what the local development config is currently set to.
=> mrc-216 generic error page

dev/cli.sh, dev/run-dependencies.sh, scripts/test-cli.sh, src/config/default.properties, src/userCLI/src/main/kotlin/org/vaccineimpact/orderlyweb/userCLI/AddMembers.kt, src/userCLI/src/main/kotlin/org/vaccineimpact/orderlyweb/userCLI/AddUser.kt, src/userCLI/src/main/kotlin/org/vaccineimpact/orderlyweb/userCLI/AddUserGroup.kt, src/userCLI/src/main/kotlin/org/vaccineimpact/orderlyweb/userCLI/App.kt, src/userCLI/src/main/kotlin/org/vaccineimpact/orderlyweb/userCLI/GrantPermission.kt, src/userCLI/src/test/kotlin/org/vaccineimpact/orderlyweb/userCLI/tests/AddMembersTests.kt, src/userCLI/src/test/kotlin/org/vaccineimpact/orderlyweb/userCLI/tests/AddPermissionTests.kt, src/userCLI/src/test/kotlin/org/vaccineimpact/orderlyweb/userCLI/tests/AddUserGroupTests.kt, src/userCLI/src/test/kotlin/org/vaccineimpact/orderlyweb/userCLI/tests/AddUserTests.kt
Turns out the java docopt parser adds square brackets to string argument values so need to strip these out before saving values.
=> the cli isn't working

src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/WebEndpoint.kt, src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/app_start/Router.kt, src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/security/authentication/AuthenticationConfig.kt, src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/viewmodels/AppViewModel.kt, src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/unit_tests/WebEndpointTests.kt, src/customConfigTests/src/test/kotlin/org/vaccineimpact/orderlyweb/customConfigTests/MontaguAuthenticationTests.kt, src/customConfigTests/src/test/kotlin/org/vaccineimpact/orderlyweb/customConfigTests/ReportPageTests.kt, src/customConfigTests/src/test/kotlin/org/vaccineimpact/orderlyweb/customConfigTests/SeleniumTest.kt
I messed up the original branch, hence odd name here!
=> Mrc-228 Bypass landing page when auth provider is Montagu

src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/controllers/web/ReportController.kt, src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/viewmodels/ReportVersionViewModel.kt, src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/unit_tests/controllers/web/ReportControllerTests.kt, src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/unit_tests/templates/VersionPageTests.kt, src/app/templates/partials/version-picker.ftl, src/app/templates/report-page.ftl, src/customConfigTests/src/test/kotlin/org/vaccineimpact/orderlyweb/customConfigTests/GithubWebTests.kt, src/customConfigTests/src/test/kotlin/org/vaccineimpact/orderlyweb/customConfigTests/ReportPageTests.kt
Replicating existing version switcher in the new app.
=> mrc-264 add version switcher to report page

src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/controllers/web/ReportController.kt, src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/viewmodels/ReportVersionViewModel.kt, src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/unit_tests/controllers/web/ReportControllerTests.kt, src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/unit_tests/templates/VersionPageTests.kt, src/app/static/src/scss/report-page.scss, src/app/static/src/scss/style.scss, src/app/templates/partials/changelog.ftl, src/app/templates/report-page.ftl
Also adds a couple of css tweaks - extra padding where I noticed it was missing.
=> add changelog tab

src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/app_start/ErrorHandler.kt, src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/security/clients/MontaguIndirectClient.kt, src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/security/clients/OrderlyWebIndirectClient.kt, src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/security/providers/khttpMontaguAPIClient.kt, src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/security/RedirectActionBuilders/MontaguIndirectClientRedirectActionBuilderTests.kt
Turns out this was actually pretty easy!
=> only redirect user to Montagu if not already logged in

src/app/static/package-lock.json, src/app/static/package.json, src/app/static/src/js/utils/reportsTable.js, src/app/static/src/tests/reportTable.test.js
Please review but don't merge as the TreeTables package will also have to be updated once that PR is closed! So first this one: https://github.com/reside-ic/TreeTables/pull/12
=> fix boolean filtering and make name filter case insensitive

src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/app_start/routing/web/WebUserGroupRouteConfig.kt, src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/viewmodels/ReportVersionViewModel.kt, src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/unit_tests/controllers/web/ReportControllerTests.kt, src/app/static/src/js/components/reports/runReport.vue, src/app/static/src/scss/partials/buttons.scss
Fixes https://vimc.myjetbrains.com/youtrack/issue/mrc-349 but also https://vimc.myjetbrains.com/youtrack/issue/mrc-350
=> fix version and changelog ordering and style dismiss link

src/app/static/src/js/components/permissions/addPermission.vue, src/app/static/src/js/components/reports/globalReportReaderRolesList.vue, src/app/static/src/js/components/reports/reportReadersList.vue, src/app/static/src/tests/components/permissions/addPermission.test.js, src/app/static/src/tests/components/reports/reportReadersList.test.js
One more shared component. This one was sufficiently complicated I felt it deserved it's own PR! Contains commits from https://github.com/vimc/orderly-web/pull/109 so should only be reviewed after merging that one.
=> mrc-360 add permission component

src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/unit_tests/templates/VersionPageTests.kt, src/app/static/src/js/report.js, src/app/templates/report-page.ftl, src/customConfigTests/src/test/kotlin/org/vaccineimpact/orderlyweb/customConfigTests/ReportPageTests.kt
Allow deep-linking of tabs without the page jumping to the anchored divs.
=> mrc-401 use different div id to hash

src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/app_start/routing/web/WebUserRouteConfig.kt, src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/controllers/web/UserGroupController.kt, src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/db/AuthorizationRepository.kt, src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/database_tests/AuthorizationRepositoryTests.kt, src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/integration_tests/helpers/WebRequestHelper.kt, src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/integration_tests/tests/web/UsersTests.kt, src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/unit_tests/controllers/web/UserGroupControllerTests.kt
I've left the paths and controllers following the same pattern as your PR for add members, as I wasn't sure if you just wanted to use the RoleController, or also change the paths to /role/whatever..
This endpoint uses DELETE method, with user email specified in the path. Not sure if that gives us grief around URL encoding, or handled by framework..
=> mrc-1288 Remove user from group

src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/app_start/routing/web/WebRoleRouteConfig.kt, src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/controllers/web/RoleController.kt, src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/db/RoleRepository.kt, src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/database_tests/RoleRepositoryTests.kt, src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/integration_tests/tests/web/RolesTests.kt, src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/unit_tests/controllers/web/RoleControllerTests.kt
Contains changes from https://github.com/vimc/orderly-web/pull/126
=> mrc-1303 Endpoint to get all roles

src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/integration_tests/tests/web/AdminPageTests.kt, src/app/static/src/js/admin.js, src/app/static/src/js/components/admin/addUserToRole.vue, src/app/static/src/js/components/admin/manageRoles.vue, src/app/static/src/js/components/admin/manageUsers.vue, src/app/static/src/tests/components/admin/manageUsers.test.js, src/app/templates/admin.ftl
At the moment just returning an unformatted list of users. Formatting the users and adding the permission management in a separate PR.
Contains commits from https://github.com/vimc/orderly-web/pull/132
=> mrc-1322 user search widget

src/app/static/src/js/components/permissions/roleList.vue, src/app/static/src/tests/components/permissions/roleList.test.js
Expander for permission lists covered here https://github.com/vimc/orderly-web/pull/143
This PR also fixes it for the role list.
=> mrc-1338 show expander if add widget is included

.travis.yml, README.md, dev/migrate-local-test.sh, dev/run-dependencies.sh, migrations/sql/V2020.01.31_1338__InitialRole.sql, scripts/migrate-common.sh, scripts/migrate-local-test.sh, src/customConfigTests/src/test/kotlin/org/vaccineimpact/orderlyweb/customConfigTests/ReportPagePermissionTests.kt, travis/run-dependencies.sh
Make Admin a built in role by adding it to the migrations. I haven't added a "readonly" column since it's just the 1 role for now - figured it's enough to have that const in the code, and if we ever end up needing the concept of a readonly role more widely we can introduce it then.
=> mrc-1337 add admin role to db

dev/add-test-users.sh, dev/run-dependencies.sh, src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/app_start/TemplateObjectWrapper.kt, src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/app_start/routing/web/WebDocumentRouteConfig.kt, src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/controllers/web/DocumentController.kt, src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/db/DocumentRepository.kt, src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/models/Document.kt, src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/viewmodels/DocumentsViewModel.kt, src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/database_tests/DocumentRepositoryTests.kt, src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/integration_tests/tests/TemplateObjectWrapperTests.kt, src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/integration_tests/tests/web/DocumentTests.kt, src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/unit_tests/controllers/web/DocumentControllerTests.kt, src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/unit_tests/templates/DocumentsPageTests.kt, src/app/static/src/scss/documents.scss, src/app/templates/documents.ftl, src/testHelpers/src/main/kotlin/org/vaccineimpact/orderlyweb/test_helpers/insertHelpers.kt
Just adds a pretty basic index page for the docs at /docs. We might want to prettify it after feedback from the users.
=> mrc-1344 documents index page

src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/Helpers.kt
pdfs can't be rendered in img tags
=> mrc-1356 don't try to render pdfs as images

src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/viewmodels/DocumentsViewModel.kt, src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/unit_tests/controllers/web/DocumentControllerTests.kt, src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/unit_tests/templates/DocumentsPageTests.kt, src/app/static/src/js/components/documents/documentList.vue, src/app/static/src/js/components/documents/file.vue, src/app/static/src/js/components/documents/fileIcon.vue, src/app/static/src/js/documents.js, src/app/static/src/scss/documents.scss, src/app/static/src/tests/components/admin/manageUserPermissions.test.js, src/app/static/src/tests/components/documents/documentList.test.js, src/app/static/src/tests/components/documents/file.test.js, src/app/templates/documents.ftl, src/config/default.properties, src/customConfigTests/src/test/kotlin/org/vaccineimpact/orderlyweb/customConfigTests/DocumentPageTests.kt, src/testHelpers/src/main/kotlin/org/vaccineimpact/orderlyweb/test_helpers/insertHelpers.kt
Adds a Vue component for rendering the docs. To test the look and feel just create and populate a local folder at under ./src/app/documents then hit the /refresh endpoint to populate the demo db.
=> mrc-1380 make documents collapsible

README.md, migrations/sql/V2020.03.04_1515__Tags.sql
I've done this in the simplest possible way, with tags just as strings related to reports or report versions (so we don't have any 'tag definition' table or anything like that).
=> mrc-1388 Tables for tags

src/app/static/src/scss/index.scss
set break word overflow on table cells
=> mrc-1405 style bug

src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/unit_tests/templates/VersionPageTests.kt, src/app/static/src/js/components/reports/reportTags.vue, src/app/static/src/js/report.js, src/app/static/src/tests/components/reports/reportTags.test.js, src/app/templates/partials/report-tab.ftl
Read-only view, editing to follow
=> mrc-1396 Display tags in report page

src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/app_start/routing/web/WebReportRouteConfig.kt, src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/app_start/routing/web/WebVersionRouteConfig.kt, src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/controllers/web/ReportController.kt, src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/db/repositories/TagRepository.kt, src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/database_tests/ReportTests.kt, src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/database_tests/TagRepositoryTests.kt, src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/database_tests/VersionTests.kt, src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/integration_tests/tests/web/TagTests.kt, src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/unit_tests/controllers/web/ReportControllerTests/TagTests.kt, src/testHelpers/src/main/kotlin/org/vaccineimpact/orderlyweb/test_helpers/insertHelpers.kt
`/update-tags/` now handles deleting and adding tags at both report and version level
=> mrc-1397 one endpoint to rule them all

src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/db/Orderly.kt, src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/db/repositories/TagRepository.kt, src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/database_tests/TagRepositoryTests.kt, src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/database_tests/VersionTests.kt
Please note the branch name here is `mrc-1476_tags2`
=> move tag retrieval to tag repo

src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/controllers/web/ReportController.kt, src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/models/RunReportMetadata.kt, src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/viewmodels/RunReportViewModel.kt, src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/unit_tests/controllers/web/ReportControllerTests/RunReportTests.kt, src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/unit_tests/templates/RunReportPageTests.kt, src/app/static/src/js/components/runReport/runReport.vue, src/app/templates/run-report-page.ftl
Actually getting dummy data for now, until orderly server endpoints go in, but this puts the backend in place in orderlyweb
=> mrc-1598 Get run report metadata and git branches from orderly server

migrations/sql/V2020.06.15_1402__RollbackOWReportVersionTrigger.sql, src/app/build.gradle, src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/db/repositories/ReportRepository.kt, src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/database_tests/ReportRepositoryTests/ReportTests.kt, src/testHelpers/src/main/kotlin/org/vaccineimpact/orderlyweb/test_helpers/insertHelpers.kt
This branch is currently on uat and showing new versions 
https://support.montagu.dide.ic.ac.uk:10443/reports/
=> Manually insert rows to orderlyweb_report_version, remove triger

src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/InsertHelpers.kt, src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/database_tests/ReportRepositoryTests/ChangelogTests.kt, src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/integration_tests/tests/api/VersionTests.kt
Just to make the changelog insert helper a bit less verbose.
=> mrc-1485 tiny refactor

src/app/static/src/js/components/publishReports/publishReports.vue, src/app/static/src/js/components/publishReports/report.vue, src/app/static/src/scss/partials/buttons.scss, src/app/static/src/scss/partials/sidebar.scss, src/app/static/src/tests/components/publishReports/publishReports.test.js
Finally, this PR adds the publishing functionality.
=> mrc-1688 publish reports page - actually hook up the publish button

src/.idea/codeStyles/Project.xml, src/app/static/src/js/components/runReport/runReport.vue, src/app/static/src/tests/components/runReport/runReport.test.js, src/customConfigTests/src/test/kotlin/org/vaccineimpact/orderlyweb/customConfigTests/RunReportPageTests.kt
Allow user to select database instances in the front-end, where used.
=> mrc-1602 report runner page - show instances if supported

scripts/install-chromedriver.sh
Consistent with vimc/montagu-proxy@7aa3a54
=> Update ChromeDriver for compatibility with Chrome 86

scripts/install-chromedriver.sh
Check the installed version of Chrome and retrieve the matching version of ChromeDriver
=> mrc-1976 Ensure ChromeDriver/Chrome compatibility

src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/ContentTypes.kt, src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/WebEndpoint.kt, src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/app_start/RouteConfig.kt, src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/integration_tests/tests/IntegrationTest.kt, src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/integration_tests/tests/web/MetricsTests.kt, src/config/detekt/baseline-main.yml
This PR adds json content type to /metrics header.
=> Mrc-2057 Metrics endpoint has incorrect content type

Dockerfile, README.md, css.Dockerfile
This should enable mrc-1605 branch to build on buildkite
NB Merging into mrc-1605
=> npm install in docker image

README.md
- Refer to our guidelines
- Point to IDEA settings
- Explain that guidelines take precedence over detekt where it can't detect transgressions
- Describe how to regenerate detekt baseline
=> mrc-2187 Improve documentation about linting

docs/spec/spec.md, src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/controllers/api/ReportRunController.kt, src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/unit_tests/controllers/api/ReportRunControllerTests.kt
=> mrc-2189 Support timeout query string parameter in run report endpoint

.github/pull_request_template.md
This shows a reminder about the [checklist](https://mrc-ide.myjetbrains.com/youtrack/articles/RESIDE-A-13/Pull-Request-guidelines) when you open a PR
Suggestions for (or edits to) the checklist itself very welcome too - it is on the KB rather than in the PR template simply because it makes it easier to edit. It was written with OW in mind but should be broadly applicable.
=> mrc-2188 Direct contributors to pull request checklist

src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/integration_tests/tests/web/RunReportPageTests.kt, src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/unit_tests/templates/RunReportPageTests.kt, src/app/static/src/js/components/runReport/runReport.vue, src/app/static/src/js/components/runReport/runReportTabs.vue, src/app/static/src/js/runReportTabs.ts, src/app/static/src/tests/components/runReport/runReport.test.ts, src/app/static/src/tests/components/runReport/runReportTabs.test.ts, src/app/templates/run-report-page.ftl
Moves `runReport` (and eventually report logs) from an ftl template to a parent Vue component `runReportTabs`.
=> mrc-2243 Create runReportTabs Vue component

buildkite/build-app.sh, buildkite/codecov.sh
=> mrc-2332 Use audited version of Codecov uploader

src/app/templates/accessibility.ftl
As requested by Kim - since some OW instances are restricted login and hence not for 'as many people as possible', this seems a better generic wording.
=> mrc-2360 Accessibility page wording change

scripts/clear-docker.sh
See mrc-2410 for details. This won't necessary solve the problem but should help eliminate Docker cleanup as the cause.
=> Make Buildkite cleanup hook more verbose/robust

src/app/static/src/js/components/errorInfo.vue, src/app/static/src/js/components/runWorkflow/runWorkflowProgress.vue, src/app/static/src/js/utils/types.ts, src/app/static/src/tests/components/runWorkflow/runWorkflowProgress.test.ts, src/customConfigTests/src/test/kotlin/org/vaccineimpact/orderlyweb/customConfigTests/RunWorkflowTests.kt
Lists previously-run workflows and displays their status. This depends on a new server endpoint.
See slide 5 of https://docs.google.com/presentation/d/1t6-52Bhwvhiqih3hy3Hmx3xGFDjHPU-rbdZ5d89jm5o/edit#slide=id.g79f381049b_0_106
=> mrc-2312 Add workflow progress page

src/app/static/src/js/components/runReport/runReport.vue
Hopefully does what it says on the tin
=> mrc-2560 Add types to runReport.vue

src/app/static/src/js/components/runWorkflow/runWorkflowProgress.vue, src/app/static/src/tests/components/runWorkflow/runWorkflowProgress.test.ts
_Before submitting please review
the [PR checklist](https://mrc-ide.myjetbrains.com/youtrack/articles/RESIDE-A-13/Pull-Request-guidelines)_
=> mrc-2557 - set v-select clearable to false

src/app/static/src/js/components/runWorkflow/runWorkflowCreate.vue, src/app/static/src/tests/components/runWorkflow/runWorkflow.test.ts, src/app/static/src/tests/components/runWorkflow/runWorkflowCreate.test.ts
_Before submitting please review
the [PR checklist](https://mrc-ide.myjetbrains.com/youtrack/articles/RESIDE-A-13/Pull-Request-guidelines)_
=> mrc-2558 remove keys from workflow metadata definition when rerunning or cloning a workflow

src/app/static/src/js/components/reportLog/runningReportDetails.vue, src/app/static/src/tests/components/reportLog/runningReportDetails.test.ts
_Before submitting please review
the [PR checklist](https://mrc-ide.myjetbrains.com/youtrack/articles/RESIDE-A-13/Pull-Request-guidelines)_
=> mrc-2563 Fixed running report page parameter alignment

src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/unit_tests/templates/VersionPage/ChangelogTabTests.kt, src/app/templates/partials/changelog.ftl
See mrc-2599 for background. To test, follow the steps to reproduce bug - should fail on master but work with this branch.
=> mrc-2599 Fix report link on changelog page

src/app/static/src/js/components/reportLog/runningReportsList.vue, src/app/static/src/tests/components/reportLog/runningReportsList.test.ts, src/customConfigTests/src/test/kotlin/org/vaccineimpact/orderlyweb/customConfigTests/RunReportPageTests.kt
- Justification for this change outlined in mrc-2333
- To test: run one or more reports, view report logs page, and check that correct report is selected
=> mrc-2333 Pre-select report on reports logs page

src/app/static/src/js/components/runWorkflow/runWorkflowReport.vue, src/app/static/src/js/featureSwitches.ts, src/app/static/src/tests/components/runWorkflow/runWorkflowReport/runWorkflowReport.test.ts
This PR adds radio button and upload input to report component.
- Upload input only accepts csv as type using accept attributes
- Displays uploaded filename
=> mrc-2715 Add Import CSV to Workflow Report Component

css.Dockerfile, src/app/static/src/js/components/runWorkflow/runWorkflowCreate.vue, src/customConfigTests/src/test/kotlin/org/vaccineimpact/orderlyweb/customConfigTests/RunWorkflowTests.kt
I added overflow-hidden to v-select template div class. This might not be the best solution but a quick fix.
=> mrc-2747 v-select styling is whack

src/app/static/src/js/components/runWorkflow/runWorkflowSummary.vue, src/app/static/src/js/components/runWorkflow/workflowSummary/reportParameter.vue, src/app/static/src/js/components/runWorkflow/workflowSummary/runWorkflowSummary.vue, src/app/static/src/js/components/runWorkflow/workflowSummary/workflowSummaryReports.vue, src/app/static/src/js/components/workflowSummary/reportParameter.vue, src/app/static/src/js/components/workflowWizard/workflowWizard.vue, src/app/static/src/js/utils/types.ts, src/app/static/src/scss/partials/workflow-summary.scss, src/app/static/src/tests/components/runWorkflow/runWorkflow.test.ts, src/app/static/src/tests/components/runWorkflow/runWorkflowSummary.test.ts, src/app/static/src/tests/components/runWorkflow/workflowSummary/reportParameter.test.ts, src/app/static/src/tests/components/runWorkflow/workflowSummary/runWorkflowSummary.test.ts, src/app/static/src/tests/components/runWorkflow/workflowSummary/workflowSummaryReports.test.ts, src/customConfigTests/src/test/kotlin/org/vaccineimpact/orderlyweb/customConfigTests/RunWorkflowTests.kt
This PR adds timeline and report boxes to workflow summary page. This is the grey side of the report.
=> Mrc-2880 - Add report boxes to workflow summary - the grey side

src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/WebEndpoint.kt, src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/security/authentication/OrderlyWebAuthenticationConfig.kt, src/customConfigTests/src/test/kotlin/org/vaccineimpact/orderlyweb/customConfigTests/NoAuthTests.kt
_Before submitting please review
the [PR checklist](https://mrc-ide.myjetbrains.com/youtrack/articles/RESIDE-A-13/Pull-Request-guidelines)_
=> Mrc 3850 test
