vimc/orderly-web

- dist.Dockerfile
- scripts/make-build-env.sh
- scripts/run-smoke-test.sh
- src/app/build.gradle
- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/app_start/GoSignal.kt
This fixes a bug with the docker build process which means the current master image is not working, because files external to the app (the static and template directories) were not included in the image. 
This also was a simple fix - creating a new base image with the static files included for the app to inherit from. To test things of this nature I have added a basic smoke test - a bash script that just runs the app image and checks the app has started by making a request to the API index. This can be run on TC.
> add dist base image that includes templates

- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/app_start/Router.kt
- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/app_start/SparkApp.kt
- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/app_start/TemplateObjectWrapper.kt
- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/controllers/web/HomeController.kt
- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/controllers/web/TemplateAnnotation.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/integration_tests/tests/TemplateObjectWrapperTests.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/unit_tests/TemplateObjectWrapperTests.kt
We want certain properties on view models serialised to json for the page js to read. 
I've added a custom `ObjectWrapper` - this is the class that freemarker uses to convert viewmodels into something the templates can use. The new class looks for properties marked with a serialise attribute and adds them to the model before passing it on to freemarker's built in `DefaultObjectWrapper`.
> mrc-226 add template object wrapper

- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/controllers/web/HomeController.kt
- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/controllers/web/ReportController.kt
- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/controllers/web/SecurityController.kt
- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/viewmodels/IndexViewModel.kt
- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/viewmodels/ReportVersionViewModel.kt
- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/viewmodels/WebloginViewModel.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/integration_tests/tests/TemplateObjectWrapperTests.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/security/clients/GithubIndirectClientTests.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/unit_tests/APIEndpointTests.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/unit_tests/templates/IndexTests.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/unit_tests/templates/LayoutTests.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/unit_tests/templates/VersionPageTests.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/unit_tests/templates/rules/FreemarkerTestRule.kt
* moved all ViewModel classes to their own files in the viewmodels directory as having them as children of other classes was making for verbose code and crowded controllers
* removed mocking from tests where unnecessary and replaced some xml parsing with jsoup
> mrc-259 preliminary refactor

- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/controllers/web/SecurityController.kt
- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/security/authentication/AuthenticationConfig.kt
- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/security/providers/GithubApiClientAuthHelper.kt
- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/viewmodels/AppViewModel.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/integration_tests/tests/TemplateObjectWrapperTests.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/unit_tests/AuthenticationConfigTests.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/unit_tests/AuthenticationRouteBuilderTests.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/unit_tests/WebEndpointTests.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/unit_tests/templates/401Tests.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/unit_tests/templates/VersionPageTests.kt
- src/app/static/src/scss/partials/buttons.scss
- src/app/static/src/scss/partials/variables.scss
- src/app/static/src/scss/style.scss
- src/app/templates/401.ftl
- src/app/templates/report-page.ftl
- src/app/templates/weblogin.ftl
- src/customConfigTests/src/test/kotlin/org/vaccineimpact/orderlyweb/customConfigTests/GithubWebTests.kt
- src/customConfigTests/src/test/kotlin/org/vaccineimpact/orderlyweb/customConfigTests/ReportPageTests.kt
- src/customConfigTests/src/test/kotlin/org/vaccineimpact/orderlyweb/customConfigTests/SeleniumTest.kt
Fixes the sidebar styling mainly, also styles the login with GitHub button as a button and persists the vertical scrollbar to stop the page width jumping when content becomes long enough to scroll.
I also changed `GitHub` to the correct spelling everywhere and added tests for the auth config class to make sure it was case insensitive.
> mrc-258 style fixes

- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/db/AuthorizationRepository.kt
- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/models/permissions/UserGroupPermission.kt
- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/viewmodels/ReportReaderViewModel.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/InsertHelpers.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/database_tests/AuthorizationRepositoryTests.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/unit_tests/controllers/web/UserControllerTests.kt
- src/customConfigTests/src/test/kotlin/org/vaccineimpact/orderlyweb/customConfigTests/ReportPageTests.kt
This change will make a test added in https://github.com/vimc/orderly-web/pull/79 fail, so after that branch is merged, master should be merged into here, and the test updated to the behaviour introduced here (a report reader who has permission through belonging to a group is 'removable' in mrc-306, but not in this branch).
> Mrc 307 Make a report reader removable only if permission is not from a user group 

- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/controllers/api/VersionController.kt
- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/db/Orderly.kt
- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/db/OrderlyClient.kt
- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/models/OrderlyEnums.kt
Fix test failure caused by readmes no longer being treated as resources in orderly: http://teamcity.montagu.dide.ic.ac.uk:8111/viewLog.html?buildId=49370&tab=buildResultsDiv&buildTypeId=montagu_Orderly_BuildOrderlyWeb
> add readme

- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/controllers/Controller.kt
- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/controllers/api/HomeController.kt
- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/controllers/api/ReportController.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/unit_tests/controllers/api/ReportControllerTests.kt
Fixes the bug with `MissingPermissonError` being thrown even when fine grained auth is turned off. Tidied up the `ReportController` test class a bit and added tests for the bug cases.
> mrc-311 don't check permissions if fine grained auth is turned off

- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/unit_tests/templates/LayoutTests.kt
- src/app/templates/index.ftl
- src/app/templates/partials/header.ftl
As with other static assets, need to be explicit about the app url otherwise will resolve relative to the domain and not work when deployed at domain/reports
I've also opportunistically fixed the report table layout, as the column widths were jumping around when the values were filtered.
> add fully qualified favicon link

- docs/spec/Version.schema.json
- docs/spec/VersionDetails.schema.json
- docs/spec/VersionIds.schema.json
- docs/spec/Versions.schema.json
- docs/spec/spec.md
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/integration_tests/tests/api/VersionTests.kt
One outcome of the change to /report/.. rather than /reports/.. in the web endpoints is that there's now a discrepancy with the API endpoints, which are all still prefixed /reports/ - I'm assuming we're ok with that? I guess for Montagu it means that our api endpoints will look like https://whatever:port/reports/api/v1/reports/etc ..? Which is kind of weird but then API paths are often pretty horrible!
We also haven't listed the onetime_token endpoint. Do we still need that?
> mrc-330 Update spec

- dev/add-test-users.sh
- dev/run-dependencies.sh
- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/WebEndpoint.kt
- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/app_start/RouteConfig.kt
- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/app_start/routing/web/WebAuthRouteConfig.kt
- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/app_start/routing/web/WebReportRouteConfig.kt
- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/controllers/web/IndexController.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/integration_tests/tests/web/IndexPageTests.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/unit_tests/controllers/web/IndexControllerTests.kt
All logged in users should be able to see the index page. They just won't see any reports unless they have permission to do so.
> mrc-341 make index route more accessible

- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/viewmodels/UserGroupViewModel.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/database_tests/UserRepositoryTests.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/unit_tests/controllers/web/UserGroupControllerTests.kt
Perhaps we should distinguish identity groups as follows? To avoid weirdness of having groups where the only member is the user whose email is the group id.
> Distinguish identity groups

- scripts/install-chromedriver.sh
- scripts/release/tag_images.py
Update chromedriver to match latest chrome version.
This also accidentally contains a couple of fixes to the `tag_images` script - they were intended for another branch but I figure no harm in including them here!
> Fix selenium tests

- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/unit_tests/templates/VersionPageTests.kt
- src/app/static/src/js/report.js
- src/app/templates/report-page.ftl
- src/customConfigTests/src/test/kotlin/org/vaccineimpact/orderlyweb/customConfigTests/ReportPageTests.kt
Fixes regression from the old reportle - should be able to link to a particular tab on the report page.
> add tab deep linking behaviour and tests

- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/app_start/RouteConfig.kt
- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/controllers/web/UserGroupController.kt
- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/viewmodels/AdminViewModel.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/integration_tests/tests/web/AdminPageTests.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/unit_tests/controllers/web/UserGroupControllerTests.kt
- src/app/templates/admin.ftl
Adding an admin page template and route. The VM has nothing in it because I figured we'd retrieve the roles etc asynchronously via the Vue components.
This doesn't really depend on https://github.com/vimc/orderly-web/pull/123 but I accidentally branched off of it so that one should be merged first!
> mrc-1290 basic admin page and route

- src/app/static/src/js/components/permissions/addReportReader.vue
- src/app/static/src/js/components/permissions/roleList.vue
- src/app/static/src/js/components/reports/globalReportReadersList.vue
- src/app/static/src/js/components/reports/reportReadersList.vue
- src/app/static/src/js/components/reports/scopedReportReaderRolesList.vue
- src/app/static/src/tests/components/permissions/addReportReader.test.js
- src/app/static/src/tests/components/reports/reportReadersList.test.js
- src/app/static/src/tests/components/reports/scopedReaderRolesList.test.js
A rename and slight refactor of the existing `addPermission` vue component to the more appropriate `addReportReader`.
> small refactor: rename addPermission to addReportReader

- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/DirectActionContext.kt
- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/app_start/routing/web/WebRoleRouteConfig.kt
- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/app_start/routing/web/WebUserRouteConfig.kt
- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/controllers/web/AdminController.kt
- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/controllers/web/RoleController.kt
- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/controllers/web/UserController.kt
- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/models/Scope.kt
- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/models/permissions/AssociatePermission.kt
- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/models/permissions/PermissionDTO.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/integration_tests/tests/web/RolesTests.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/integration_tests/tests/web/UsersTests.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/unit_tests/controllers/web/RoleControllerTests.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/unit_tests/controllers/web/UserControllerTests.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/unit_tests/models/ScopeTests.kt
- src/app/static/src/js/components/permissions/addPermission.vue
- src/app/static/src/js/components/permissions/roleList.vue
- src/app/static/src/js/components/reports/reportReadersList.vue
- src/app/static/src/tests/components/permissions/addPermission.test.js
- src/app/static/src/tests/components/permissions/roleList.test.js
- src/app/static/src/tests/components/reports/reportReadersList.test.js
- src/app/static/src/tests/components/reports/scopedReaderRolesList.test.js
Replaces the `associate-permission` endpoints with 2 separate POST and DELETE endpoints. Contains commits from https://github.com/vimc/orderly-web/pull/137
> RESTful refactor

- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/controllers/web/ReportController.kt
- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/viewmodels/AppViewModel.kt
- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/viewmodels/IndexViewModel.kt
- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/viewmodels/ReportVersionViewModel.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/integration_tests/tests/TemplateObjectWrapperTests.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/unit_tests/controllers/web/ReportControllerTests.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/unit_tests/templates/DefaultViewModelTests.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/unit_tests/templates/IndexTests.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/unit_tests/templates/LayoutTests.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/unit_tests/templates/VersionPageTests.kt
- src/app/templates/partials/header.ftl
- src/app/templates/report-page.ftl
- src/customConfigTests/src/test/kotlin/org/vaccineimpact/orderlyweb/customConfigTests/FineGrainedPermissionTests.kt
As well as removing the "coming soon" tooltip and wiring up the link from the report page, I've added an admin link to the header. Had to re-jig the VMs a bit to make `isAdmin` a base VM property, and made `isReviewer` a base VM one while I was at it, given it's shared between report and index pages. I also added a separate `fineGrainedAuth` property to the base VM so that it can be used as needed in the templates. This seemed like the simplest approach for readability and testability.
> mrc-1327 wire up admin link

- src/app/static/package-lock.json
- src/app/static/package.json
- src/app/static/src/js/components/admin/addUserToRole.vue
- src/app/static/src/js/components/permissions/addReportReader.vue
- src/app/static/src/js/components/reports/reportReadersList.vue
- src/app/static/src/js/components/typeahead/typeahead.vue
- src/app/static/src/js/components/typeahead/typeaheadList.vue
- src/app/static/src/js/components/typeahead/typeaheadListItem.vue
- src/app/static/src/tests/components/typeahead/typeahead.test.js
- src/app/static/src/tests/components/typeahead/typeaheadList.test.js
- src/app/static/src/tests/components/typeahead/typeaheadListItem.test.js
The npm typeahead package seems to be dead, so I just pulled in the source code along with the fix for keyboard navigation from this PR on that repo: https://github.com/alexurquhart/vue-bootstrap-typeahead/pull/29
> mrc-1335 should be able to use keys to select values from typeahead

- src/app/static/src/js/components/admin/rolePermissionsList.vue
- src/app/static/src/tests/components/admin/rolePermissionsList.test.js
Roles in the role permission list should be shown as expandable, and should be clickable, to show the add permission  component. This was not the case - permission list was not included if no child permissions.,
> mrc-1339 Make roles with no permissions expandable

- dev/migrate-local-test.sh
- src/customConfigTests/src/test/kotlin/org/vaccineimpact/orderlyweb/customConfigTests/AdminPageTests.kt
I found that ./dev/run-dependencies.sh wasn't working after that last merge because it was trying to create the orderly demo twice. I've modified migrate-local-test.sh to specify the expected demo path from $HERE. Does that make sense?
> Specify local path where orderly demo might already be located

- .gitignore
- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/ActionContext.kt
- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/DirectActionContext.kt
- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/Helpers.kt
- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/app_start/RouteConfig.kt
- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/app_start/routing/web/WebDocumentRouteConfig.kt
- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/controllers/Controller.kt
- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/controllers/api/ArtefactController.kt
- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/controllers/web/DocumentController.kt
- src/app/src/main/resources/config.properties
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/integration_tests/tests/web/DocumentTests.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/unit_tests/controllers/web/DocumentControllerTests.kt
- src/app/src/test/resources/config.properties
- src/config/default.properties
Endpoint to get a single document, locked down to the global `documents.read` permission. Supports inline browser viewing as well as download functionality.
Contains commits from https://github.com/vimc/orderly-web/pull/153
> mrc-1345 endpoint to get single document

- scripts/release/make-release.py
To test run ./script/release/make-release.py on this branch, the parent ticket of which has quotes in the name (but don't push the commit it creates!)
> mrc-1367 release script should handle quotes in ticket names

- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/app_start/routing/api/ReportRouteConfig.kt
- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/app_start/routing/api/VersionRouteConfig.kt
- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/app_start/routing/web/WebVersionRouteConfig.kt
- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/controllers/api/ReportController.kt
- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/db/Orderly.kt
- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/db/OrderlyClient.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/database_tests/ReportTests.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/integration_tests/tests/api/VersionTests.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/integration_tests/tests/web/VersionTests.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/unit_tests/controllers/api/ReportControllerTests.kt
Rather than round tripping publishing via orderly server, just update the db directly.
> mrc-1368 publish reports without hitting orderly server

- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/errors/ExpiredToken.kt
- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/security/authentication/OrderlyWebBearerTokenAuthenticator.kt
- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/security/clients/APIActionAdaptor.kt
- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/security/clients/JWTHeaderClient.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/integration_tests/helpers/APIRequestHelper.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/integration_tests/tests/api/auth/SecurityTests.kt
So that a 401 with a clear message is returned rather an unexpected error from a null reference exception.
> throw custom exception if token is expired

- docs/spec/VersionDetails.schema.json
- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/db/Orderly.kt
- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/models/Report.kt
- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/models/ReportVersionDetails.kt
- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/viewmodels/IndexViewModel.kt
- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/viewmodels/ReportVersionViewModel.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/database_tests/VersionTests.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/integration_tests/tests/TemplateObjectWrapperTests.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/unit_tests/controllers/api/ReportControllerTests.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/unit_tests/controllers/api/VersionControllerTests.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/unit_tests/controllers/web/IndexControllerTests.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/unit_tests/controllers/web/ReportControllerTests.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/unit_tests/templates/IndexTests.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/unit_tests/templates/VersionPageTests.kt
- src/app/static/src/js/index.js
- src/app/static/src/js/utils/reportsTable.js
- src/app/static/src/tests/indexReader.test.js
- src/app/static/src/tests/indexReviewer.test.js
- src/app/static/src/tests/reportTable.test.js
- src/app/templates/index.ftl
- src/app/templates/partials/report-tab.ftl
- src/testHelpers/src/main/kotlin/org/vaccineimpact/orderlyweb/test_helpers/insertHelpers.kt
This shows parameter values in both the Index page and the Report details page. 
I've made the parameter values a string map in the backend models, which then get turned into strings to render in both the Index and Report view models - that seemed more flexible if we want to change the view in future, though it means there's a bit of duplicated code when the view models are built.
> Mrc 1370 Show report version parameter values

- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/Files.kt
- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/controllers/api/DocumentController.kt
- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/db/DocumentRepository.kt
- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/models/Document.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/database_tests/DocumentRepositoryTests.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/integration_tests/tests/TemplateObjectWrapperTests.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/unit_tests/FileTests.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/unit_tests/controllers/api/DocumentControllerTests.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/unit_tests/controllers/web/DocumentControllerTests.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/unit_tests/templates/DocumentsPageTests.kt
Contains commits from https://github.com/vimc/orderly-web/pull/174
What I haven't done here is update the index page itself, so any external links will currently link to the .url text file on disk, rather than the external link. But those changes will be made on a separate branch, and should be done after https://github.com/vimc/orderly-web/pull/173 is merged as well.
> mrc-1382 backend for external file links

- docs/spec/spec.md
- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/app_start/routing/api/GitRouteConfig.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/integration_tests/tests/api/GitTests.kt
Removes the /reports/ modifier from git endpoints. Leaves the deprecated endpoints in place as this is a breaking change. Once references to the endpoints are updated in orderly these can be deleted.
> mrc-1386 disambiguate git endpoints

- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/app_start/routing/api/ReportRouteConfig.kt
- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/app_start/routing/api/VersionRouteConfig.kt
- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/db/Orderly.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/PermissionChecker.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/integration_tests/APIPermissionChecker.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/integration_tests/WebPermissionChecker.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/integration_tests/helpers/APIRequestHelper.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/integration_tests/tests/IntegrationTest.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/integration_tests/tests/RoutingTests.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/integration_tests/tests/api/ArtefactTests.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/integration_tests/tests/api/DataTests.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/integration_tests/tests/api/GitTests.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/integration_tests/tests/api/ReportTests.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/integration_tests/tests/api/ResourceTests.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/integration_tests/tests/api/UserTests.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/integration_tests/tests/api/VersionTests.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/integration_tests/tests/api/ZipTests.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/integration_tests/tests/web/VersionPageTests.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/integration_tests/tests/web/VersionTests.kt
- src/testHelpers/src/main/kotlin/org/vaccineimpact/orderlyweb/test_helpers/insertHelpers.kt
We introduced a permission checking utility for web endpoints but didn't do the same for api endpoints. As a result api tests are more laborious to write and less consistent (and in some places, tests that endpoints were secure were missing). This PR adds a permission checker for api endpoints and uses it where relevant.
In the course of adding this I found that we were not correctly testing endpoints that were secured with scoped report reading permissions and indeed the logic for doing so had a bug in it. So this has also been fixed and the web tests updated.
> mrc-1408 add security testing util for api

- src/app/static/externals.config.js
- src/app/static/src/js/index.js
- src/app/templates/index.ftl
the index bundle is over the recommended bundle size and we get a webpack warning about it. this just pulls out the datatables related files from the bundle to keep the size down
> mrc-1457 pull out datatables files from bundle

- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/db/Orderly.kt
- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/models/Changelog.kt
- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/viewmodels/ReportVersionViewModel.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/database_tests/OrderlyChangelogTests.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/unit_tests/controllers/api/ReportControllerTests.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/unit_tests/controllers/api/VersionControllerTests.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/unit_tests/controllers/web/ReportControllerTests/GetByNameAndVersionTests.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/unit_tests/templates/VersionPageTests.kt
- src/app/templates/partials/changelog.ftl
Bug - see screenshot in ticket https://mrc-ide.myjetbrains.com/youtrack/issue/mrc-1478
This is because the css style rules are for classes `public` and `internal` but the labels in the Montagu instance are "external" and "internal". In fact these labels are totally customizable, so we shouldn't be relying on them anyway, rather we can construct the css class from the "changelog_label.public" field in the db,
> mrc-1478 bug fix - styling not applied for public changelog items

- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/Helpers.kt
- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/Serializer.kt
- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/controllers/api/ArtefactController.kt
- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/controllers/api/VersionController.kt
- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/controllers/web/ReportController.kt
- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/db/Orderly.kt
- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/db/OrderlyClient.kt
- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/models/Report.kt
- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/models/ReportVersion.kt
- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/models/ReportVersionDetails.kt
- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/viewmodels/IndexViewModel.kt
- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/viewmodels/ReportVersionViewModel.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/database_tests/VersionTests.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/integration_tests/tests/TemplateObjectWrapperTests.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/unit_tests/controllers/api/ArtefactControllerTests.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/unit_tests/controllers/api/ReportControllerTests.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/unit_tests/controllers/api/VersionControllerTests.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/unit_tests/controllers/web/IndexControllerTests.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/unit_tests/controllers/web/ReportControllerTests/GetByNameAndVersionTests.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/unit_tests/controllers/web/ReportControllerTests/TagTests.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/unit_tests/templates/VersionPageTests.kt
Prior to factoring out a `ReportRepository` and `ReportLogic`, this refactors the `ReportVersion` models - this is so that the repo can return basic objects derived from the `REPORT` and `REPORT_VERSION` tables and then the logic class can compose the complex objects that require also fetching from other tables (`ARTEFACT`, `RESOURCE`, etc.)
> mrc-1476 refactor report related models

- src/app/static/src/js/components/admin/manageRolePermissions.vue
- src/app/static/src/js/components/admin/manageUserPermissions.vue
- src/app/static/src/js/components/admin/permissionList.vue
- src/app/static/src/tests/components/admin/manageRolePermisisons.test.js
- src/app/static/src/tests/components/admin/manageUserPermissions.test.js
- src/app/static/src/tests/components/admin/permissionList.test.js
I wondered about not showing the Admin permissions at all rather than showing them without user being able to change them - but it could be useful to be able to see the permissions you'd be giving a user by putting them in the Admin role.
> mrc-1490 Make Admin role non-editable in front end

- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/db/Orderly.kt
- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/db/repositories/ReportRepository.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/database_tests/ReportRepositoryTests/ReportTests.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/database_tests/ReportRepositoryTests/VersionTests.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/database_tests/VersionTests.kt
Moves the initial data retrieval part of the `Orderly` method `getAllReportVersions` into the report repo.  
Contains commits from https://github.com/vimc/orderly-web/pull/222
Most of this changeset is re-writing tests.
> mrc-1476 refactor getAllReportVersions

- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/app_start/routing/web/WebReportRouteConfig.kt
- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/controllers/web/ReportController.kt
- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/viewmodels/RunReportViewModel.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/integration_tests/tests/web/RunReportPageTests.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/unit_tests/controllers/web/ReportControllerTests/RunReportTests.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/unit_tests/templates/RunReportPageTests.kt
- src/app/static/src/js/components/runReport/runReport.vue
- src/app/static/src/js/runReport.js
- src/app/static/src/tests/components/runReport/runReport.test.js
- src/app/templates/run-report-page.ftl
- src/customConfigTests/src/test/kotlin/org/vaccineimpact/orderlyweb/customConfigTests/RunReportPageTests.kt
This branch just wires up a route, page and front end component for the run report functionality, no actual content yet. 
- Adds a run-report route 
- Adds a template page, which includes tabs for 'Run report' and 'Report logs' and an element picked up by the front end to show..
- ..a placeholder runReport vue component, which will contain the report runner form, and handle requests to backend to fetch details and run report. 
There is already a runReport vue component, in the reports folder. This is the simple runner from the reportVersion page, which will be removed when this work is completed. 
There is no link to the new page from the index page, but you can see it by browsing to /run-report.
> mrc-1604 Run report placeholder page and vue component

- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/app_start/routing/web/WebReportRouteConfig.kt
- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/controllers/web/ReportController.kt
- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/db/repositories/ReportRepository.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/database_tests/ReportRepositoryTests/VersionTests.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/integration_tests/tests/web/ReportTests.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/unit_tests/controllers/web/ReportControllerTests/PublishTests.kt
Adds a web endpoint, locked down to report reviewers, that accepts a list of ids and publishes the corresponding reports.
> mrc-1687 add endpoint for bulk publishing

- src/app/static/src/js/components/reports/runReportInline.vue
- src/app/static/src/js/report.js
- src/app/static/src/tests/components/reports/runReportInline.test.js
- src/app/templates/report-page.ftl
At the moment, the new report version link appears before the version page actually exists. I found this recently when running a report and it was very confusing! I thought something had gone wrong and so ended up running the report multiple times.
> mrc-1684 only show new version when run is complete

- src/app/static/src/js/components/publishReports/publishReports.vue
- src/app/static/src/tests/components/publishReports/publishReports.test.js
Contains commits from https://github.com/vimc/orderly-web/pull/249 which should be merged first, then the base of this PR set to master.
> mrc-1689 option to only show previously published reports on bulk publish page

- src/app/static/src/js/components/publishReports/dateGroup.vue
- src/app/static/src/js/components/publishReports/publishReports.vue
- src/app/static/src/js/components/publishReports/reportDraft.vue
- src/app/static/src/tests/components/publishReports/publishReports.test.js
- src/app/static/src/tests/components/publishReports/reportDraft.test.js
As requested by Kim on the mockups, a way to open/close all changelogs on the page at once.
Contains commits from https://github.com/vimc/orderly-web/pull/249, should be merged first and the base of this PR returned to `master`.
There are some file conflicts, probably easiest to merge https://github.com/vimc/orderly-web/pull/251 first and then I'll fix them.
> mrc-1690 expand/collapse all changelogs on bulk publish page

- src/.idea/codeStyles/Project.xml
- src/app/static/src/js/components/publishReports/dateGroup.vue
- src/app/static/src/js/components/publishReports/publishReports.vue
- src/app/static/src/js/components/publishReports/report.vue
- src/app/static/src/js/components/publishReports/reportDraft.vue
- src/app/static/src/tests/components/publishReports/dateGroup.test.js
- src/app/static/src/tests/components/publishReports/publishReports.test.js
- src/app/static/src/tests/components/publishReports/report.test.js
- src/app/static/src/tests/components/publishReports/reportDraft.test.js
This PR adds the ability to select report drafts (by report, date, or individually), ahead of being able to publish them. For another ticket - a select all / deselect all option will be useful.
> mrc-1688 publish report page - allow reports to be selected 

- scripts/docker-compose.yml
Should be merged along with https://github.com/vimc/montagu-proxy/pull/54
> vimc-4228 always use public docker hub for proxy image

- src/.idea/codeStyles/Project.xml
- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/OrderlyServerAPI.kt
- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/errors/OrderlyServerError.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/unit_tests/OrderlyServerTests.kt
Previously our usage of the API has been very simple - OW endpoints just make a single request and pass it straight back out to the client, so no parsing of responses, and we just pass the status code and text along.
With the runner we will need to make multiple calls to the API in a single OW request and e.g. combine the results into a viewmodel. So this PR adds some utilities to the orderly server API client to help with that:
* parsing response data
* option to throw on error
> mrc-1601 add utils to orderlyserver api client

- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/HttpClient.kt
- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/OrderlyServerAPI.kt
- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/app_start/routing/api/ReportRouteConfig.kt
- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/controllers/api/ReportController.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/integration_tests/APIPermissionChecker.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/integration_tests/helpers/APIRequestHelper.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/integration_tests/tests/api/ReportTests.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/unit_tests/OrderlyServerTests.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/unit_tests/controllers/api/ReportControllerTests.kt
To be used by diagnostic report runner task when receiving request to run report for a group/disease who already have a report run in progress.
> mrc-1898 Add kill running report endpoint

- README.md
- app.Dockerfile
- buildkite/build-app.sh
This produces a coverage report using JaCoCo and uploads it to Codecov.
It works slightly differently to [Travis](https://github.com/vimc/orderly-web/blob/master/.travis.yml#L48) and [HINT](https://github.com/mrc-ide/hint/pull/381/files). OrderlyWeb is built and tested in a container, inside which neither the Buildkite environment or git repository are available, so we use Codecov's suggested approach to pass the relevant variables (Codecov token, git commit and branch identifiers etc) to the container at runtime.
> mrc-2036 Add Codecov to Buildkite

- src/build.gradle
- src/gradle/wrapper/gradle-wrapper.properties
Bump Kotlin to latest point release (1.3.72) as precursor to fixing any deprecations and eventually upgrading to Kotlin 1.4.
This requires a point-upgrade of Gradle for compatibility with the Kotlin plugin, which was performed by:
```sh
./gradlew wrapper --gradle-version 4.9
```
> mrc-2043 Update Kotlin to latest v1.3.x

- README.md
- app.Dockerfile
- buildkite/build-app.sh
- buildkite/pipeline.yml
- src/app/build.gradle
Implemented:
* Provide access to detekt and junit summary reports, as well as full results (as a zip file) as Buildkite [artifacts](https://buildkite.com/mrc-ide/orderly-web/builds/156#025ac072-14e8-46bd-af4f-046469741c3f)
* Correspondingly reduce verbosity of logging during junit tests (in particular htmlunit, incidentally addressing mrc-1829)
* Remove redundant `CI_ENV` variable and necessity to specify git commit and branch for Codecov
* Don't push Docker image unless build succeeds
Notes:
* Artefacts are stored by Buildkite in Amazon S3. The relevant buckets have un-guessable URLs but are not private. I don't think that our JaCoCo, detekt or Junit reports contain any sensitive information, so this shouldn't be a problem.
* As noted on mrc-2025, the ideal situation would be to simply …
> mrc-2025 Save kotlin HTML test logs as build artefacts

- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/OrderlyServerAPI.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/unit_tests/OrderlyServerTests.kt
- src/config/detekt/detekt.yml
- src/customConfigTests/src/test/kotlin/org/vaccineimpact/orderlyweb/customConfigTests/RunReportPageTests.kt
This PR reverts a [recent change](https://github.com/vimc/orderly-web/commit/0993220ed4a6de4bba7a16822ac6f83c1f90ab3d#diff-1aafe52916a7595c2dc2e7dc95e9ed446fd9e8c2e4d56bfc6e896c9d8907dcd7R154) that added a `?` to the end of orderly.server API calls - which was problematic for reasons described in mrc-2065. It adds two tests that would have identified this issue.
This changeset also changes the detekt configuration to relax ktlint's formatting rules, as this is the first time they have been tested in anger for new code. Unfortunately those disabled include the basic indentation rule, which apparently can't be used in combination with our braces-on-newlines convention. This is not inconsistent with HINT, as it does not have any formatting rules enabled (it does not use the …
> mrc-2065 Correctly handle requests with query parameters in OrderlyServerAPI

- src/app/static/package-lock.json
- src/app/static/package.json
Update gulp-sass in order to bump node-sass to version compatible with Node 14, retaining compatibility with Node 10 and 12.
> mrc-2155 Ensure compatibility with current version of Node (14/LTS)

- src/app/build.gradle
- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/OrderlyServerAPI.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/PermissionChecker.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/integration_tests/APIPermissionChecker.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/integration_tests/WebPermissionChecker.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/integration_tests/helpers/APIRequestHelper.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/integration_tests/helpers/RequestHelper.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/integration_tests/helpers/WebRequestHelper.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/integration_tests/tests/IntegrationTest.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/integration_tests/tests/api/BundleTests.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/integration_tests/tests/api/ZipTests.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/integration_tests/tests/api/auth/MontaguAuthenticationTests.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/unit_tests/DirectActionContextTests.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/unit_tests/OrderlyServerTests.kt
- src/config/detekt/baseline-main.yml
- src/customConfigTests/build.gradle
- src/customConfigTests/src/test/kotlin/org/vaccineimpact/orderlyweb/customConfigTests/CustomConfigTests.kt
- src/customConfigTests/src/test/kotlin/org/vaccineimpact/orderlyweb/customConfigTests/FineGrainedPermissionTests.kt
- src/customConfigTests/src/test/kotlin/org/vaccineimpact/orderlyweb/customConfigTests/GithubAuthenticationTests.kt
- src/customConfigTests/src/test/kotlin/org/vaccineimpact/orderlyweb/customConfigTests/RequestHelper.kt
- src/testHelpers/build.gradle
- src/testHelpers/src/main/kotlin/org/vaccineimpact/orderlyweb/test_helpers/RequestHelpers.kt
- src/testHelpers/src/main/kotlin/org/vaccineimpact/orderlyweb/test_helpers/http/HttpClient.kt
We currently use both OkHttp and khttp for HTTP requests. khttp is unmaintained. This changeset removes our dependency on it by introducing a new HttpClient class which broadly presents the same API in order to minimise code churn.
Implementation notes:
- Unlike khttp, OkHttp does transparent gzip - but only if you _don’t_ specify a Accept-Encoding on requests (even if this encoding is gzip!). So we remove this header where specified explicitly.
- Unlike khttp, OkHttp doesn’t automatically store cookies. These are only needed by our tests when redirection takes place - so this feature is enabled only where necessary.
- OkHttp is updated to the latest version compatible with the version of Kotlin that we're using (1.3)
- A direct dependency on org.json is added (it was previously …
> mrc-2024 Remove final usages of khttp

- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/app_start/routing/web/WebReportRouteConfig.kt
- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/controllers/web/ReportController.kt
- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/db/repositories/ReportRepository.kt
- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/models/GitCommit.kt
- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/models/Report.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/database_tests/ReportRepositoryTests/ReportTests.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/integration_tests/tests/web/RunReportPageTests.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/unit_tests/OrderlyServerTests.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/unit_tests/controllers/web/ReportControllerTests/ListReportsTests.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/unit_tests/controllers/web/ReportControllerTests/RunnableReportsTests.kt
- src/config/detekt/baseline-main.yml
Adds new `/list-reports/` endpoint. It retrieves the list of available reports from orderly.server and uses the orderly database to annotate them with details of the "last run" date for those that have previously been executed. It accepts optional `branch` and `commit` query parameters where the relevant orderly store has `git_supported` (i.e. when there is a `.git` folder and `master_only` isn't true). This endpoint has been configured to require the `reports.run` permission because it has been added as part of the implementation of the new `/run-report` page (mrc-1595).
Notes:
- When "joining" the full list of reports from orderly.server with the list of report versions from the database we first retrieve every version of every report. This is a single query but could conceivably result …
> mrc-1599 Endpoint to get all reports user can run

- src/app/static/jest.config.js
- src/app/static/package-lock.json
- src/app/static/package.json
- src/app/static/src/js/components/runReport/reportList.vue
- src/app/static/src/js/components/runReport/runReport.vue
- src/app/static/src/tests/components/runReport/reportList.test.js
- src/app/static/src/tests/components/runReport/runReport.test.js
- src/customConfigTests/src/test/kotlin/org/vaccineimpact/orderlyweb/customConfigTests/RunReportPageTests.kt
This builds on #283 to expand support for running reports via OrderlyWeb to report selection itself:
* Re-orders the form and makes it slightly more wizard-like: moving "Database instance" below "Report" (as it is effectively a runtime parameter) and conditionally displaying each form input based on the previous
* It supports orderly stores with git enabled and disabled. In the latter case the git branch and commit selectors are hidden.
* It uses the vanilla [vue-typeahead-bootstrap](https://github.com/alexurquhart/vue-bootstrap-typeahead) component. We have an old version of a related (unmaintained) project in our source tree but it enforces some constraints that aren't applicable here. This isn't ideal - it could be updated/amended but I'm wary of collateral damage.
* Given the …
> mrc-1603 Run report page: user can select report to run

- src/app/static/src/js/components/runReport/reportList.vue
- src/app/static/src/js/components/runReport/runReport.vue
- src/app/static/src/tests/components/runReport/runReport.test.js
- src/customConfigTests/src/test/kotlin/org/vaccineimpact/orderlyweb/customConfigTests/RunReportPageTests.kt
It may be a bit premature to put this in, as a couple of other tickets/clarifications need to be resolved which will require modification of the `run` request - but it's probably good to get something in early to actually get reports running. 
Please note:
- There were no changes required to the backend as the existing run endpoint, simply passes through the request to orderly server
- I am confused about instances - we have our metadata and vue set up to assume there can be multiple instances, however the interface for orderly server only accepts a single instance. I've asked Rob to clarify, will check with him when I get back from leave. Since we seem to be getting a map of metadata instances from OS, I think its run endpoint just needs to be updated. 
- To run up the page with runnable …
> mrc-1606 Add run report button and temporary status check

- docs/spec/spec.md
- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/OrderlyServerAPI.kt
- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/app_start/routing/api/ReportRouteConfig.kt
- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/app_start/routing/web/WebReportRouteConfig.kt
- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/controllers/api/ReportController.kt
- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/controllers/api/ReportRunController.kt
- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/db/repositories/ReportRunRepository.kt
- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/models/ReportRun.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/database_tests/ReportRunRepositoryTests.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/integration_tests/tests/api/ReportTests.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/unit_tests/OrderlyServerTests.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/unit_tests/controllers/api/ReportControllerTests.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/unit_tests/controllers/api/ReportRunControllerTests.kt
- src/app/static/src/js/components/runReport/runReport.vue
- src/app/static/src/tests/components/runReport/runReport.test.js
- src/config/detekt/baseline-main.yml
This is a fair amount of code to do something quite simple: add a row to the database when a report is run. It doesn't cover updating the row as the job progresses, or retrieving rows from the table - they are the subject of subsequent tickets.
Summary of code changes:
- Enable requests to orderly.server from OrderlyWeb backend, rather than only passing through requests from front-end
- POST only for now
- Passed-through responses should probably be refactored to re-use new logic (i.e. old `post` method calls new `post` method)
- Split `ReportController`, creating a `ReportRunController` (URLs remain unchanged)
- Log report runs to database, using new `OrderlyWebReportRunRepository` class
- Modify front-end to send a dict of instances rather than just a string (where the values in the map …
> Add row to orderlyweb_runningreport when run a report

- README.md
- src/app/static/gulpfile.js
- src/app/static/package-lock.json
- src/app/static/package.json
Adds a `watch` task to our Gulp config that can be invoked as follows:
```sh
npm run watch --prefix src/app/static
```
This will watch the front-end code and rebuild it as necessary. Note that it doesn't watch the css files or our external JavaScript dependencies - this could be added but these change much less frequently.
Also apply a neutral fix to `package-lock.json` to fix a mysterious dependency resolution problem that is preventing me from doing a clean `npm install`.
> Implement basic live-reload for front-end code

- README.md
- buildkite/make-db.sh
- dev/run-dependencies.sh
- src/.idea/codeStyles/Project.xml
- src/app/build.gradle
- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/db/repositories/ReportRepository.kt
- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/models/ReportVersionWithArtefactsDataDescParamsResources.kt
- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/models/ReportVersionWithDescLatestElapsed.kt
- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/viewmodels/ReportVersionViewModel.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/database_tests/OrderlyTests.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/database_tests/ReportRepositoryTests/VersionTests.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/integration_tests/tests/TemplateObjectWrapperTests.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/unit_tests/controllers/api/VersionControllerTests.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/unit_tests/controllers/web/ReportControllerTests/GetByNameAndVersionTests.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/unit_tests/templates/VersionPage/MetadataTabTests.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/unit_tests/templates/VersionPage/VersionPageTestData.kt
- src/app/templates/partials/metadata-tab.ftl
- src/config/detekt/baseline-main.yml
- src/customConfigTests/src/test/resources/hoverfly/github-oauth2-login.json
- src/testHelpers/src/main/kotlin/org/vaccineimpact/orderlyweb/test_helpers/insertHelpers.kt
Adds start and elapse time to the report version page metadata tab. 
This involved adding the `elapsed` property a new report version variant data class. 
This branch is deployed to UAT, where you can see how it displays some real report elapsed times e.g [here](https://support.montagu.dide.ic.ac.uk:10443/reports/report/paper-second-summarise-with-unique-data/20201209-145215-a8c89a46#metadata)
Also updated dependencies to run with latest `create_orderly_demo` and fixed failing customConfig tests
Not sure why codecov is failing, the line it's complaining about is definitely tested e.g. [here](https://github.com/vimc/orderly-web/pull/315/files#diff-c43e5bc7d771cca4fb3157c1ed102c76cd67d8d4b7f331a551c1616fed0d9e50R109)
> mrc-2174 Show start time and elapsed on metadata tab

- buildkite/build-app.sh
- buildkite/build-cli.sh
- buildkite/common
- buildkite/run-custom-config-tests-in-container.sh
- buildkite/run-smoke-test.sh
Move `cleardocker` exit handler from `common` to scripts that require it i.e. those that invoke `docker run`
> Ensure interrupted orderly-web CI builds are cleaned-up

- src/customConfigTests/src/test/kotlin/org/vaccineimpact/orderlyweb/customConfigTests/RunReportPageTests.kt
See mrc-2149 for background.
Explanation:
* The previously failing test runs a report and then checks that the execution log looks correct
* The test suite uses a different orderly.sqlite file to the one being updated by orderly.server (see [here](https://github.com/vimc/orderly-web/blob/master/src/customConfigTests/src/test/kotlin/org/vaccineimpact/orderlyweb/customConfigTests/CustomConfigTests.kt#L40))
* The test only passes if at least part of the log is returned before the job finishes. If the logs are only returned on completion (which now seems to be the case, at least for this short-running job, but I guess would also be the case if a job finishes instantaneously), then the logs can't be stored in the orderlyweb_report_run table because the insert also tries to set the …
> mrc-2419 Fix Selenium test for report-running progress

- src/app/static/package-lock.json
- src/app/static/package.json
Pinned to git branch for QA purposes - will be updated to `1.2.1` on TreeTables release following merge of reside-ic/TreeTables#32
> mrc-1925 Update TreeTables to improve performance with large number of reports

- README.md
- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/Annotations.kt
- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/app_start/routing/web/WebWorkflowRouteConfig.kt
- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/controllers/web/WorkflowRunController.kt
- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/models/WorkflowRun.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/integration_tests/tests/web/WorkflowRunTests.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/unit_tests/controllers/web/WorkflowRunControllerTests.kt
- src/config/detekt/baseline-main.yml
This basically switches from passing through [orderly.server response](https://github.com/vimc/orderly.server/blob/master/inst/schema/WorkflowStatus.schema.json) for workflow status to constructing our [own response](https://github.com/vimc/orderly-web/pull/351/files#diff-dff48e9479fe9b6280d0afa5ecaaa0e280232ac01ad361f397263d8f3ad9d97aR319), principally to include report names (as needed for the workflow progress page), but also to exclude fields we don't need (per-report queue status) or are already retrieved via other endpoints (report logs).
I've tried to address the recurring issue of having to add redundant code to tests just to ensure coverage of data classes by adding a `NoCoverage` annotation (aliased because JaCoCo only ignores classes annotated with something included …
> Add report names to workflow status response

- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/app_start/routing/web/WebReportRouteConfig.kt
- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/controllers/web/ReportController.kt
- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/models/RunReportMetadata.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/integration_tests/tests/web/ReportTests.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/unit_tests/controllers/web/ReportControllerTests/RunReportTests.kt
Both mrc-2310 (add reports to workflow) and mrc-2311 (finalise workflow) require report run metadata. This metadata is also used by the run report page, where it is injected into the template by the backend. However, it makes more sense for the more autonomous workflow wizard child components to fetch this metadata themsevles. This ticket adds the endpoint and modifies the controller to use the same methods to fetch metadata for both usages. 
The metadata endpoint actually returns both the metadata object and the list of initial git branches.
> mrc-2467 Add endpoint to get report run metadata

- src/app/build.gradle
- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/controllers/web/SecurityController.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/unit_tests/controllers/web/SecurityControllerTests.kt
- src/config/detekt/baseline-main.yml
- src/customConfigTests/src/test/kotlin/org/vaccineimpact/orderlyweb/customConfigTests/GithubWebTests.kt
Fixes bug where if you request a url like `weblogin?requestedUrl=<<<<"ksrcdg%20>>>545454` the requested url was interpreted as html and displayed in the page. 
This actually somewhat concerning as I thought that Freemarker templates did HTML encoding for us, but perhaps not in attributes? We should investigate this.. But this should fix this particular issue!
> mrc-2486 HTML encode requested url in Github login template

- src/app/static/src/js/components/runReport/changeLog.vue
- src/app/static/src/js/components/runReport/runReport.vue
- src/app/static/src/js/utils/types.ts
- src/app/static/src/tests/components/runReport/changeLog.test.ts
- src/app/static/src/tests/components/runReport/runReport.test.ts
This PR separates changeLog component from runReport component. This was necessary to have a clean implementation for mrc-2311. Components implementation and tests are self-explanatory and should be easy to review.
Please ignore the mrc-name, I have separated changeling for reusability.
> mrc-2311_git create an independent component for changelog

- src/app/static/src/js/components/runWorkflow/runWorkflowCreate.vue
- src/app/static/src/js/components/runWorkflow/runWorkflowProgress.vue
- src/app/static/src/js/utils/types.ts
- src/app/static/src/tests/components/runWorkflow/runWorkflow.test.ts
- src/app/static/src/tests/components/runWorkflow/runWorkflowCreate.test.ts
- src/app/static/src/tests/components/runWorkflow/runWorkflowProgress.test.ts
Following our discussion earlier, I thought it would be worth refactoring the metadata types as agreed in a separate branch to the other changes in this ticket, so that the new metadata type for submission is available for Nick's ticket ASAP. 
There are fields which are common for both submitting workflows, and the workflow details used when creating a new workflow from an existing workflow. These are:
- name
- reports
- instances
- git_branch
- git_commit
In addition, for submission, there is:
- changelog
..and for returned workflow details there are:
- date
- email
- key
However, we do not need a type for the details response since the code in `runWorkflowCreate` which fetches that just uses destructuring to immediately translate it into a RunWorkflowMetadata, without key etc, and the …
> mrc-2511_types Refactor workflow metadata types

- src/app/static/src/js/components/runReport/changeLog.vue
- src/app/static/src/js/components/runReport/instances.vue
- src/app/static/src/js/components/runWorkflow/runWorkflowRun.vue
- src/app/static/src/tests/components/runReport/changeLog.test.ts
- src/app/static/src/tests/components/runReport/instances.test.ts
- src/app/static/src/tests/components/runWorkflow/runWorkflowRun.test.ts
- src/customConfigTests/src/test/kotlin/org/vaccineimpact/orderlyweb/customConfigTests/RunWorkflowTests.kt
This branch brings `runWorkflowRun`, the finalise workflow page, into line with `runWorkflowReport` by having it emit any workflow metadata changes to the wizard rather than managing them internally. This means the that metadata will be updated ready to be submitted when user presses 'Run workflow'. 
It also means that it should be possible to go back to the previous step, then forward again to the finalise change, and see that any changes previously made have been retained. This required updating the changelog and instances components to support mounting with initial values.
> mrc-2511 Emit changes in runWorkflowRun to persist then in workflow metadata

- src/app/static/src/js/components/runReport/changeLog.vue
- src/app/static/src/js/components/runReport/runReport.vue
- src/app/static/src/js/components/runWorkflow/runWorkflowRun.vue
- src/app/static/src/tests/components/runReport/changeLog.test.ts
- src/app/static/src/tests/components/runReport/runReport.test.ts
- src/app/static/src/tests/components/runWorkflow/runWorkflowRun.test.ts
- Modify the `<change-log>` component to emit an object `{type, message}` rather than `type` and `message` strings separately, and make corresponding changes to downstream components for running reports and workflows
- This is better because a changelog with an empty message is invalid and rejected by orderly
- So the component now only emits valid changelog items: either `null` (which means no changelog and is already removed by Kotlin before request is sent to orderly.server) or an fully populated object
- This means that `runWorkflowMetadata` never contains values for `changelog` that aren't valid - which was previously the case and prevented workflows that didn't have a changelog message from being executed successfully (obviously only the case where changelog itself was enabled i.e. …
> mrc-2559 Avoid submitting empty changelog with workflow definition

- scripts/docker-compose.yml
I found that local dependencies were still intermittently failing to start the orderly server container. The error logged was `Error in redis_connect_tcp... Failed to create context: Connection refused.` suggesting that the redis container was not available when orderly server started up - but needs to be.
Updated the docker compose file to specify that the orderly server container depends on the redis container, meaning that redis will be started before orderly server. (see https://docs.docker.com/compose/compose-file/compose-file-v3/#depends_on)
This *seems* to have fixed the problem - @richfitz does this sound plausible?
> mrc-2593 Make orderly server container depends on redis container

- src/app/static/src/js/components/runWorkflow/runWorkflowReport.vue
- src/app/static/src/tests/components/runWorkflow/runWorkflowReport/runWorkflowReport.test.ts
- Truncate label and make full name available via tooltip
- Also fix header sizes - previously all `<h2>`
- We could also potentially increase `col-sm-2` to `col-sm-3` to allow more of the name to be displayed - we have the horizontal space to do this without reducing width of other inputs. But this would require similar change to git component, and therefore report running page too (unless we make width configurable via props, or change page layouts to be more automatically adaptive).
- To test:
- Run app, using git model
- Create a new report with a long name:
```shell
docker exec -it -w /orderly/upstream/src montagu_orderly_server_1 bash
cp -r global new_report_with_a_much_longer_name
git add .
git commit -m new_report
```
- Go to http://localhost:8888/run-workflow
- Create a blank …
> mrc-2625 Fix workflow display of long report names

- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/ActionContext.kt
- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/DirectActionContext.kt
- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/OrderlyServerAPI.kt
- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/controllers/web/ReportController.kt
- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/controllers/web/WorkflowRunController.kt
- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/errors/BadRequest.kt
- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/logic/WorkflowLogic.kt
- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/models/Report.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/integration_tests/tests/IntegrationTest.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/integration_tests/tests/web/RunReportPageTests.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/integration_tests/tests/web/WorkflowRunTests.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/unit_tests/DirectActionContextTests.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/unit_tests/OrderlyServerTests.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/unit_tests/controllers/web/ReportControllerTests/RunReportTests.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/unit_tests/controllers/web/ReportControllerTests/RunnableReportsTests.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/unit_tests/controllers/web/WorkflowRunControllerTests.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/unit_tests/controllers/web/reportControllerTests/GetByNameAndVersionTests.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/unit_tests/controllers/web/reportControllerTests/MetadataTests.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/unit_tests/controllers/web/reportControllerTests/PinnedReportTests.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/unit_tests/controllers/web/reportControllerTests/PublishReportsTests.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/unit_tests/controllers/web/reportControllerTests/PublishTests.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/unit_tests/controllers/web/reportControllerTests/RunReportTests.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/unit_tests/controllers/web/reportControllerTests/RunnableReportsTests.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/unit_tests/controllers/web/reportControllerTests/TagTests.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/unit_tests/errors/ExceptionTests.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/unit_tests/logic/WorkflowLogicTests.kt
This branch:
- adds logic to `WorkflowLogic` to validate uploaded workflow csv rows against reports in Orderly as follows:
- checks that report name exists
- checks that all required parameters (those with no defaults) have been provided. A parameter value is considered to be provided if is not an empty string i.e. whitespace is ok. This is consistent with behaviour of run report form. 
- checks that no unexpected parameters have been provided
- all report rows are checked, and all errors found are included in report, with indication of row number ('Report row number', counting from 1 i.e. excluding header - does that seem clear enough?) 
- Because this requires fetching report and parameter information from Orderly, helper methods have been added to `OrderlyServerAPI` to do this, which …
> mrc-2720 Validate workflow csv against orderly

- css.Dockerfile
- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/logic/WorkflowLogic.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/integration_tests/tests/web/WorkflowRunTests.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/unit_tests/logic/WorkflowLogicTests.kt
This branch uses file row number rather than 'report row numbers' (i.e. not including header rows) in import CSV workflow error messages, as suggested [in this PR](https://github.com/vimc/orderly-web/pull/399). Also adds column numbers where possible.
> mrc-2822 Import csv validation errors use file row numbers and column numbers

- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/integration_tests/tests/web/WorkflowRunTests.kt
- src/testHelpers/src/main/kotlin/org/vaccineimpact/orderlyweb/test_helpers/JSONValidator.kt
Using JSONValidator with schema containing `$ref` was failing - this branch adds inline dereferencing to the schema factory config to support this, and adds a validation check to the workflow summary integration test to check that this works (this check would fail on master)
> mrc-2825 Support dereferencing in JSONValidator

- src/app/static/src/js/components/runReport/gitUpdateReports.vue
- src/app/static/src/js/components/runReport/runReport.vue
- src/app/static/src/js/components/runWorkflow/runWorkflowReport.vue
- src/app/static/src/tests/components/runReport/gitUpdateReports.test.ts
- src/app/static/src/tests/components/runReport/runReport.test.ts
- src/app/static/src/tests/components/runWorkflow/runWorkflowReport/runWorkflowReport.test.ts
- src/app/static/src/tests/components/runWorkflow/runWorkflowReport/runWorkflowReport_validation.test.ts
- src/customConfigTests/src/test/kotlin/org/vaccineimpact/orderlyweb/customConfigTests/RunReportPageTests.kt
- src/customConfigTests/src/test/kotlin/org/vaccineimpact/orderlyweb/customConfigTests/RunWorkflowTests.kt
This branch uses the new `show_all` flag for the runnable reports endpoint, when called from the run workflow component (but not from the run single report endpoint). 
Setting the `show_all` flag means that all reports available in the branch are returned, not just the ones which have changes in the branch. Getting branch-specific reports only is useful for Run report, since user will only be interested in reports with changes - however, in Run workflow, the user is also likely to want to run dependencies which may not have changed. 
Can be tested manually with the orderly demo - on 'other' branch, the master branch reports 'global' and 'minimal' were previously not displayed in Run workflow, but they are with these changes. They are still absent in 'other' branch in Run report.
> mrc-2829 Pass show_all flag to runnable reports endpoint for run workflow

- src/app/static/package-lock.json
- src/app/static/package.json
- src/app/static/src/js/components/runWorkflow/workflowSummary/workflowSummaryReports.vue
- src/app/static/webpack.config.js
The workflow tabs bundle had become massive again (> 1.5MiB)
* adds the bundle analyser plugin to frotn-end dependencies, for future debugging
* switches import from bootstrap-vue to use more specific syntax which avoids pulling in the whole library
> mrc-2948 fix oversize js bundle

- docs/spec/Status.schema.json
- src/customConfigTests/src/test/kotlin/org/vaccineimpact/orderlyweb/customConfigTests/GithubAuthenticationTests.kt
- src/customConfigTests/src/test/kotlin/org/vaccineimpact/orderlyweb/customConfigTests/GithubWebTests.kt
- src/customConfigTests/src/test/resources/hoverfly/github-oauth2-login.json
This branch reinstates changes which we want to retain from the mrc-2966 PR (which needed to be reverted), specifically:
- [Update to the Status schema](https://github.com/vimc/orderly-web/pull/439/files/f4f5f6f3c311b76a2024ecd8aa02ee6ae970b821..3a0435860cb87363a57515388598fb1cdf8fbd22#diff-8b491b3e219ed8963a25957d5dd54b91b9b30541ad6ffd3907927be12fc2d831R20) to reflect new response from Orderly Server. This prevents integration test failure.
-  [Add missing custom config tests](https://github.com/vimc/orderly-web/pull/439/files#diff-dabbbd38377cb364be9e9b8c54e4795eb0bd75c2a283d0dc24f9bb3b84435fb8R95) for case where user is required to be github team member (using web login), with required updates to the config for Hoverfly (which mocks Github API).
This branch also adds tests for GitHub …
> mrc-2995 Update status schema and add missing github auth tests

- config/orderly_server_version
- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/controllers/web/WorkflowRunController.kt
- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/db/repositories/WorkflowRunRepository.kt
- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/models/WorkflowRun.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/database_tests/WorkflowRunRepositoryTests.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/integration_tests/tests/web/WorkflowRunTests.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/unit_tests/controllers/web/WorkflowRunControllerTests.kt
- src/build.gradle
Update run workflow endpoint to expect the new orderly server response, and explicitly sort by executon order when returning workflow report statuses.
> mrc-3033 save and return execution order of workflow reports

- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/integration_tests/tests/api/ReportTests.kt
Fixes the build failure caused by orderly server change: https://github.com/vimc/orderly.server/pull/98
When user attempts to kill a report with a non-existent key, OS now returns a 200 rather than a 400, but with a message indicating that the report did not exist. 
The test which was failing is primarily testing that the endpoint returns a 403 when user does not have permissions to kill reports - which is still the case - and contrasting that with the 400 previously returned for user with perms for non-existent jey. Because of this, it seems sufficient to just update the expected status code for the user with perms in this test.
> mrc-3137 Expect 200 status when user with perms kills non-existent report

- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/logic/WorkflowLogic.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/integration_tests/tests/web/WorkflowRunTests.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/unit_tests/OrderlyServerTests.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/unit_tests/logic/WorkflowLogicTests.kt
This fixes the bug where you cannot add an unchanged report to a workflow csv on a branch other than master 
I've added a check for this to an existing integration test but let me know if more suitable as a separate test.
I have been able to check this works but running the app locally and uploading a csv manually
> Validate workflow CSV against all available reports

- Dockerfile
- buildkite/common
- customConfigTests.Dockerfile
- dist.Dockerfile
- scripts/install-chromedriver.sh
- src/.idea/compiler.xml
- src/.idea/gradle.xml
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/database_tests/ReportRepositoryTests/ReportTests.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/database_tests/ReportRunRepositoryTests.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/database_tests/WorkflowRunReportRepositoryTests.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/database_tests/WorkflowRunRepositoryTests.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/integration_tests/tests/web/ReportLogsTests.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/integration_tests/tests/web/WorkflowRunTests.kt
- src/build.gradle
- src/customConfigTests/src/test/resources/hoverfly/github-oauth2-login.json
- src/userCLI/Dockerfile
Upgrade to Java 11. A few minor changes to the docker images, update to datetime tests to account for the fact that datetime precision coming out of the db is now only to milliseconds, and a change to the hoverfly code as apparently `keep-alive` header is no longer being set. Is the latter a problem?! Manual testing suggests not, the login flow works as expected when I run it locally. I have deployed this to UAT but can't test it because vpn access not working :roll_eyes:
> mrc-3068 upgrade to Java 11

- docs/spec/Artefact.schema.json
- docs/spec/FileInfo.schema.json
- docs/spec/VersionDetails.schema.json
- docs/spec/spec.md
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/integration_tests/tests/api/VersionTests.kt
The spec/schema for `GET reports/:name/versions/:version` was wrong. This updates the integration test to actually pick this up (see https://github.com/vimc/orderly-web/pull/471/commits/e3be3248487ea09b8122ce76175e6f6aba8780c4 for failing test prior to schema change), and fixes the spec/schema so that it matches the behaviour of the endpoint.
> mrc-3401 fix bug in spec

- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/app_start/SparkApp.kt
- src/customConfigTests/build.gradle
- src/customConfigTests/src/test/kotlin/org/vaccineimpact/orderlyweb/customConfigTests/CustomConfigTests.kt
- src/customConfigTests/src/test/kotlin/org/vaccineimpact/orderlyweb/customConfigTests/FineGrainedPermissionTests.kt
- src/customConfigTests/src/test/kotlin/org/vaccineimpact/orderlyweb/customConfigTests/GithubAuthenticationTests.kt
- src/customConfigTests/src/test/kotlin/org/vaccineimpact/orderlyweb/customConfigTests/SeleniumDebugHelper.kt
- src/customConfigTests/src/test/kotlin/org/vaccineimpact/orderlyweb/customConfigTests/SeleniumTest.kt
- src/testHelpers/src/main/kotlin/org/vaccineimpact/orderlyweb/test_helpers/http/HttpClient.kt
Adds some more checks before tests execute:
* is the template db available
* is the copied db available
* has the previous Spark instance stopped
Given flakiness it's hard to say whether this has fixed the issues, but I did re-run the last build 3 times and get 3 consecutive passes.
> Add more DB/app readiness checks in between tests to fix flakiness

- scripts/release/requirements.txt
Not sure if this will completely alleviate the package install problems, but Rich thinks it will be a good start. The agents have been updated to ubuntu 22. If there is still an issue after this upgrade we can have a look at https://mrc-ide.myjetbrains.com/youtrack/issue/RESIDE-325
> Update version of requirements in buildkite build

- buildkite/common
This is so we can set this in orderly.server to trigger a build of OW with a specific version of orderly.server to test if changes to orderly.server will break OW. If `ORDERLY_SERVER_VERSION` env var is not set this will fallback to existing behaviour
We will then trigger a build from orderly.server like
```
- trigger: "orderly-web"
label: ":rocket: orderly-web (from orderly.server) :cloud:"
env:
ORDERLY_SERVER_VERSION: "${BUIDLKITE_COMMIT}"
```
> Use env var to set orderly server version

- scripts/docker-compose.yml
- src/app/build.gradle
- src/app/orderly_demo/orderly_config.yml
- src/customConfigTests/src/test/kotlin/org/vaccineimpact/orderlyweb/customConfigTests/CustomConfigTests.kt
- src/customConfigTests/src/test/kotlin/org/vaccineimpact/orderlyweb/customConfigTests/OrderlyConfig.kt
- src/customConfigTests/src/test/kotlin/org/vaccineimpact/orderlyweb/customConfigTests/RunReportPageTests.kt
This PR introduces parameterized tests as a way of running things against different orderly configs. If we like this pattern we can make most or all tests into parameterized tests; some will simply run multiple times, some will contain conditional assertions depending on the config type, as in this example.
~~Depends on https://github.com/vimc/orderly-web/pull/495~~
> mrc-3664 introduced a first parameterized test

- src/app/static/src/js/components/runWorkflow/runWorkflow.vue
- src/app/static/src/js/components/runWorkflow/runWorkflowReport.vue
- src/app/static/src/js/components/runWorkflow/workflowSummary/runWorkflowSummary.vue
- src/app/static/src/js/components/runWorkflow/workflowSummary/workflowSummaryReports.vue
- src/customConfigTests/src/test/kotlin/org/vaccineimpact/orderlyweb/customConfigTests/RunReportPageTests.kt
- src/customConfigTests/src/test/kotlin/org/vaccineimpact/orderlyweb/customConfigTests/RunWorkflowTests.kt
This rolls out the parameterized test approach to all the tests that involve report/workflow running. In doing so I did find a couple small UI bugs, which I fixed. Where tests use git related functionality I have made the assertions conditional, otherwise just declared them as parameterized tests so they run for both cases, but assertions are identical.
> mrc-3934 make end-to-end report running tests run against different orderly configs

- docs/spec/Error.schema.json
- docs/spec/ErrorCode.schema.json
- scripts/run-dependencies.sh
- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/OrderlyServerClient.kt
- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/OutpackServerClient.kt
- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/PorcelainAPI.kt
- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/app_start/SparkApp.kt
- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/app_start/routing/api/OutpackRouteConfig.kt
- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/controllers/Controller.kt
- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/controllers/api/BundleController.kt
- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/controllers/api/OutpackController.kt
- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/controllers/api/QueueController.kt
- src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/errors/PorcelainError.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/integration_tests/tests/IntegrationTest.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/integration_tests/tests/api/BundleTests.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/integration_tests/tests/api/OutpackTests.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/integration_tests/tests/web/GitTests.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/unit_tests/PorcelainAPIClientTests.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/unit_tests/controllers/api/BundleControllerTests.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/unit_tests/controllers/api/OutpackControllerTests.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/unit_tests/controllers/api/ReportRunControllerTests.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/unit_tests/controllers/web/WorkflowRunControllerTests.kt
- src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/unit_tests/controllers/web/reportControllerTests/RunReportTests.kt
- src/customConfigTests/src/test/kotlin/org/vaccineimpact/orderlyweb/customConfigTests/GithubAuthenticationTests.kt
- src/testHelpers/src/main/kotlin/org/vaccineimpact/orderlyweb/test_helpers/http/HttpClient.kt
At the moment, if a `PorcelainAPI` instance has the `throwOnError` flag, a generic exception is raised. This PR changes this so that the error detail from the porcelain API is passed through as the exception message.
> mrc-2183 pass through error details even when using throwOnError

- Dockerfile
- src/app/static/package.json
- src/app/static/src/js/components/runWorkflow/runWorkflowReport.vue
- src/app/static/src/scss/index.scss
- src/app/static/src/tests/components/runWorkflow/runWorkflowReport/runWorkflowReport.test.ts
- src/customConfigTests/src/test/kotlin/org/vaccineimpact/orderlyweb/customConfigTests/RunWorkflowTests.kt
This fixes a couple of regressions I noticed on HIV deployment (you can see this on prod at hiv-orderly.dide.ic.ac.uk)
* It fixes styling on treetables, at the moment the arrow at the start of a row and the show pointer on hover are broken. I am guessing this is since https://github.com/vimc/orderly-web/pull/490 ? It fixes this styling by dropping the file extension on the included css
* When a user uploads a workflow csv, if there are any issues in the csv those errors are not reported back out to the user. I think this changed since switch from `message` to `detail` https://github.com/vimc/orderly-web/pull/506/files#diff-9b20cef9b37dc4c8a4eadf6dbfd9b873ad70bffc45880e7b72bde15cb4b925c4L5
> vimc-7028: Fix workflow csv upload errors not being shown
